---
# Use the current username with "admin" appended as the default remote
# username (with passwordless sudo).
ansible_user: "{{ lookup('env', 'USER') }}admin"

# If a jump host is specified, add the appropriate command line parameters for
# ssh.
ansible_ssh_common_args: "-J {{ ssh_jump_host | default(omit) }}"

# administrative users
admin_users:
  - username: kms15
    fullname: Kendrick Shaw
  - username: eric
    fullname: Eric Herman
  - username: ace
    fullname: Stephanie Medlock
