---
# Use the current username with "admin" appended as the default remote
# username (with passwordless sudo).
ansible_user: "{{ lookup('env', 'USER') }}admin"

# If a jump host is specified, add the appropriate command line parameters for
# ssh.
ansible_ssh_common_args: "-oProxyJump={{ ssh_jump_host | default(omit) }}"

# administrative users
admin_users:
  - username: kms15
    fullname: Kendrick Shaw
  - username: eric
    fullname: Eric Herman
  - username: ace
    fullname: Stephanie Medlock

# Put all of the subnets and IP addresses in one place to make it easier to
# avoid collisions.
oel_subnets:
    bos1_public:
        name: bos1.openelectronicslab.org
        subnet: 192.168.1.0
        netmask: 255.255.255.0
        broadcast: 192.168.1.255
        gateway: 192.168.1.1
        hosts:
            morchella0:
                #ip: 154.3.222.74
                ip: 192.168.1.147
            boletus0:
                #ip: 154.3.222.75
                ip: 192.168.1.64
            boletus1:
                #ip: 154.3.222.76
                ip: 192.168.1.65
            boletus2:
                #ip: 154.3.222.77
                ip: 192.168.1.66
            boletus3:
                #ip: 154.3.222.78
                ip: 192.168.1.67
    bos1_management:
        name: management.bos1.openelectronicslab.org
        subnet: 172.16.0.0
        netmask: 255.255.255.0
        broadcast: 172.16.0.255
        gateway: 172.16.0.1
        hosts:
            morchella0:
                ip: 172.16.0.1
            boletus0:
                ip: 172.16.0.2
                mac: 00:25:90:76:08:2c
                pxe_file: pxelinux.0
            boletus0-ipmi:
                ip: 172.16.0.3
                mac: 00:25:90:76:06:31
            boletus1:
                ip: 172.16.0.4
                mac: 00:25:90:17:08:3e
            boletus1-ipmi:
                ip: 172.16.0.5
                mac: 00:25:90:76:06:3a
            boletus2:
                ip: 172.16.0.6
                mac: 00:25:90:17:08:0c
            boletus2-ipmi:
                ip: 172.16.0.7
                mac: 00:25:90:76:06:21
            boletus3:
                ip: 172.16.0.8
                mac: 00:25:90:17:07:e2
            boletus3-ipmi:
                ip: 172.16.0.9
                mac: 00:25:90:76:06:0c
    bos1_backend:
        name: backend.bos1.openelectronicslab.org
        subnet: 172.16.8.0
        netmask: 255.255.248.0
        broadcast: 172.16.15.255
        gateway: 172.16.4.1
        hosts:
            boletus0:
                ip: 172.16.8.10
            boletus1:
                ip: 172.16.8.11
            boletus2:
                ip: 172.16.8.12
            boletus3:
                ip: 172.16.8.13
