---
# Use the current username with "admin" appended as the default remote
# username (with passwordless sudo).
ansible_user: "{{ lookup('env', 'USER') }}admin"

# If a jump host is specified, add the appropriate command line parameters for
# ssh.
ansible_ssh_common_args: "-oProxyJump={{ ssh_jump_host | default(omit) }}"

# administrative users
admin_users:
  - username: kms15
    fullname: Kendrick Shaw
  - username: eric
    fullname: Eric Herman
  - username: ace
    fullname: Stephanie Medlock

oel_subnets:
    bos1_management:
        name: management.bos1.openelectroncslab.org
        subnet: 172.16.0.0
        netmask: 255.255.255.0
        broadcast: 172.16.0.255
        gateway: 172.16.0.1
        hosts:
            morchella0:
                ip: 172.16.0.1
            boletus0:
                ip: 172.16.0.2
            boletus0-ipmi:
                ip: 172.16.0.3
            boletus1:
                ip: 172.16.0.4
            boletus1-ipmi:
                ip: 172.16.0.5
            boletus2:
                ip: 172.16.0.6
            boletus2-ipmi:
                ip: 172.16.0.7
            boletus3:
                ip: 172.16.0.8
            boletus3-ipmi:
                ip: 172.16.0.9
    bos1_backend:
        name: backend.bos1.openelectroncslab.org
        subnet: 172.16.8.0
        netmask: 255.255.248.0
        broadcast: 172.16.15.255
        gateway: 172.16.4.1
        hosts:
            boletus0:
                ip: 172.16.8.10
            boletus1:
                ip: 172.16.8.11
            boletus2:
                ip: 172.16.8.12
            boletus3:
                ip: 172.16.8.13
