---
# Use the current username with "admin" appended as the default remote
# username (with passwordless sudo).
ansible_user: "{{ lookup('env', 'USER') }}admin"

# jump host example
#ssh_jump_host: kendrickshaw.org

# If a jump host is specified, add the appropriate command line parameters for
# ssh.
#ansible_ssh_common_args: "-oProxyJump={{ ssh_jump_host | default(omit) }}"

guest_vms: []

# default to full disk encryption
full_disk_encryption: true

# administrative users
admin_users:
  - username: kms15
    fullname: Kendrick Shaw
  - username: eric
    fullname: Eric Herman
  - username: ace
    fullname: Stephanie Medlock

# Put all of the subnets and IP addresses in one place to make it easier to
# avoid collisions.
oel_subnets:
    bos1_public:
        name: bos1.openelectronicslab.org
        subnet: 154.3.222.72
        netmask: 255.255.255.248
        broadcast: 153.3.222.79
        gateway: 154.3.222.73
        dns:
          - 1.1.1.1
          - 1.0.0.1
        hosts:
            morchella0:
                ip: 154.3.222.74
            boletus0: # /dev/enp3s0f1
                ip: 154.3.222.75
                mac: 00:25:90:76:08:2d
            boletus1:
                ip: 154.3.222.76
            boletus2:
                ip: 154.3.222.77
            boletus3:
                ip: 154.3.222.78

    bos1_management:
        name: management.bos1.openelectronicslab.org
        subnet: 172.16.0.0
        netmask: 255.255.255.0
        broadcast: 172.16.0.255
        gateway: 172.16.0.1
        dns:
          - 1.1.1.1
          - 1.0.0.1
        hosts:
            morchella0:
                ip: 172.16.0.1
                dhcp_range: 172.16.0.192 172.16.0.254
            boletus0: # /dev/enp3s0f0
                ip: 172.16.0.2
                mac: 00:25:90:76:08:2c
                pxe_file: pxelinux.0
            boletus0-ipmi:
                ip: 172.16.0.3
                mac: 00:25:90:76:06:31
            boletus1:
                ip: 172.16.0.4
                mac: 00:25:90:76:08:3e
                pxe_file: pxelinux.0
            boletus1-ipmi:
                ip: 172.16.0.5
                mac: 00:25:90:76:06:3a
            boletus2:
                ip: 172.16.0.6
                mac: 00:25:90:76:08:0c
                pxe_file: pxelinux.0
            boletus2-ipmi:
                ip: 172.16.0.7
                mac: 00:25:90:76:06:21
            boletus3:
                ip: 172.16.0.8
                mac: 00:25:90:76:07:e2
                pxe_file: pxelinux.0
            boletus3-ipmi:
                ip: 172.16.0.9
                mac: 00:25:90:76:06:0c

    bos1_backhaul:
        name: backhaul.bos1.openelectronicslab.org
        subnet: 172.16.1.0
        netmask: 255.255.255.0
        broadcast: 172.16.1.255
        gateway: 172.16.1.1
        dns:
          - 1.1.1.1
          - 1.0.0.1
        hosts:
            boletus0:
                ip: 172.16.1.10
            boletus1:
                ip: 172.16.1.11
            boletus2:
                ip: 172.16.1.12
            boletus3:
                ip: 172.16.1.13

    bos1_wg_backhaul:
        name: wg-backhaul.bos1.openelectronicslab.org
        subnet: 172.16.2.0
        netmask: 255.255.255.0
        CIDR: 24
        broadcast: 172.16.2.255
        gateway: 172.16.2.1
        dns:
          - 1.1.1.1
          - 1.0.0.1
        hosts:
            boletus0:
                ip: 172.16.2.10
            boletus1:
                ip: 172.16.2.11
            boletus2:
                ip: 172.16.2.12
            boletus3:
                ip: 172.16.2.13

    bos1_vpn_boletus0_private:
        name: private.vpn.boletus0.bos1.openelectronicslab.org
        subnet: 172.16.4.0
        netmask: 255.255.255.0
        broadcast: 172.16.4.255
        gateway: 172.16.4.1
        dns:
          - 1.1.1.1
          - 1.0.0.1
        hosts:
            boletus0:
                ip: 172.16.4.1

    bos1_vpn_boletus1_private:
        name: private.vpn.boletus1.bos1.openelectronicslab.org
        subnet: 172.16.5.0
        netmask: 255.255.255.0
        broadcast: 172.16.5.255
        gateway: 172.16.5.1
        dns:
          - 1.1.1.1
          - 1.0.0.1
        hosts:
            boletus1:
                ip: 172.16.5.1

    bos1_vpn_boletus2_private:
        name: private.vpn.boletus2.bos1.openelectronicslab.org
        subnet: 172.16.6.0
        netmask: 255.255.255.0
        broadcast: 172.16.6.255
        gateway: 172.16.6.1
        dns:
          - 1.1.1.1
          - 1.0.0.1
        hosts:
            boletus2:
                ip: 172.16.6.1

    bos1_vpn_boletus3_private:
        name: private.vpn.boletus3.bos1.openelectronicslab.org
        subnet: 172.16.7.0
        netmask: 255.255.255.0
        broadcast: 172.16.7.255
        gateway: 172.16.7.1
        dns:
          - 1.1.1.1
          - 1.0.0.1
        hosts:
            boletus3:
                ip: 172.16.7.1
            testvm3:
                ip: 172.16.7.2

