---
# During boot, /dev/sda is the USB and /dev/sdb is the SSD
# after boot, USB becomes /dev/sdd and SSD becomes /dev/sda
installer_target_drive: /dev/sdb
usb_key: /dev/sdd
luks_additional:
    rust_sdb: /dev/sdb
    rust_sdc: /dev/sdc

network_interfaces:
    #enp3s0f0: # disabled for security
    #   subnet: "{{ oel_subnets.bos1_management }}"
    enp3s0f1:
        subnet: "{{ oel_subnets.bos1_public }}"
    ibp2s0:
        subnet: "{{ oel_subnets.bos1_backhaul }}"
primary_interface: enp3s0f1

pxe_mac: "{{ oel_subnets.bos1_management.hosts[
    inventory_hostname_short].mac }}"

kvm_lvm_pools:
    ssd0_pool:
        device: /dev/mapper/sdb2_crypt
        volume_group: "{{ inventory_hostname_short }}-vg"

kvm_volumes:
    test_volume:
        pool: ssd0_pool
        size: 8G

bridges:
    br0:
        subnet: "{{ oel_subnets[
            'bos1_vpn_' + inventory_hostname_short + '_private'] }}"
