---
# During boot, /dev/sda is the USB and /dev/sdb is the SSD
# after boot, USB becomes /dev/sdd and SSD becomes /dev/sda
installer_target_drive: /dev/sdb
usb_key: /dev/sdd
luks_additional:
    rust_sdb: /dev/sdb
    rust_sdc: /dev/sdc

visible_subnets:
  - "{{ oel_subnets['bos1_public0'] }}"
  - "{{ oel_subnets['bos1_public1'] }}"
  - "{{ oel_subnets['bos1_management'] }}"
  - "{{ oel_subnets['bos1_backhaul'] }}"
  - "{{ oel_subnets['bos1_wg_backhaul'] }}"
  - "{{ oel_subnets['bos1_vpn_boletus0_private'] }}"
  - "{{ oel_subnets['bos1_vpn_boletus1_private'] }}"
  - "{{ oel_subnets['bos1_vpn_boletus2_private'] }}"
  - "{{ oel_subnets['bos1_vpn_boletus3_private'] }}"

network_interfaces:
    #enp3s0f0: # disabled for security
    #   subnet: "{{ oel_subnets.bos1_management }}"
    enp3s0f1:
        subnet: "{{ oel_subnets.bos1_public0 }}"
    ibp2s0:
        subnet: "{{ oel_subnets.bos1_backhaul }}"
primary_interface: enp3s0f1

wireguard_public_subnet: "{{ oel_subnets.bos1_backhaul }}"
wireguard_private_subnet: "{{ oel_subnets.bos1_wg_backhaul }}"

pxe_mac: "{{ oel_subnets.bos1_management.hosts[
    inventory_hostname_short].mac }}"

ipmi_lan_channel: 1
ipmi_lan_ip: "{{ oel_subnets.bos1_management.hosts[
    inventory_hostname_short + '-ipmi'].ip }}"
ipmi_lan_netmask: "{{ oel_subnets.bos1_management.netmask }}"
ipmi_lan_gateway: "{{ oel_subnets.bos1_management.gateway }}"

kvm_lvm_pools:
    ssd0_pool:
        device: /dev/mapper/sdb2_crypt
        volume_group: "{{ inventory_hostname_short }}-vg"

kvm_volumes: {}

bridges:
    br0:
        subnet: "{{ oel_subnets[
            'bos1_vpn_' + inventory_hostname_short + '_private'] }}"

load_balancer_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;vault0
          64663832616163643532303234616438666263396633393337326534633761383661376461326237
          3039633336323535643061653136303138343661666631350a643133323963623535356462376438
          61336532306364636465656463396665663837396263626466626365306330633233303064396534
          3161633333653062630a306432643132376237336634656666303439316530303761326635643734
          6632

load_balancer_lvs_sync: boletuslb0_backhaul

load_balancers:
    boletuslb0_public:
        interface: enp3s0f1
        virtual_router_id: 51
        virtual_ipaddress: "{{ oel_subnets.bos1_public1.hosts.boletuslb0.ip
            }}/{{ oel_subnets.bos1_public1.CIDR }}"
    boletuslb0_backhaul:
        interface: ibp2s0
        virtual_router_id: 52
        virtual_ipaddress: "{{ oel_subnets.bos1_backhaul.hosts.boletuslb0.ip
            }}/{{ oel_subnets.bos1_backhaul.CIDR }}"
