---
# Turn off disk encryption by default (since the host's disk should already be
# encrypted).
full_disk_encryption: false

installer_target_drive: /dev/vda

network_interfaces:
    enp1s0:
        subnet: "{{ oel_subnets[
            'bos1_vpn_' + hostvars[kvm_host].inventory_hostname_short + '_private'] }}"
primary_interface: enp1s0
ssh_jump_host: "{{ lookup('env', 'USER') }}admin@{{ kvm_host }}"
ansible_ssh_common_args: "-oServerAliveInterval=3 -oProxyJump={{ ssh_jump_host | default(omit) }}"

grub_cmdline_linux: "console=ttyS0 nomodeset raid=noautodetect"

visible_subnets:
  - "{{ oel_subnets['bos1_public0'] }}"
  - "{{ oel_subnets['bos1_public1'] }}"
  - "{{ oel_subnets['bos1_backhaul'] }}"
  - "{{ oel_subnets['bos1_wg_backhaul'] }}"
  - "{{ oel_subnets['bos1_vpn_boletus0_private'] }}"
  - "{{ oel_subnets['bos1_vpn_boletus1_private'] }}"
  - "{{ oel_subnets['bos1_vpn_boletus2_private'] }}"
  - "{{ oel_subnets['bos1_vpn_boletus3_private'] }}"
  - "{{ oel_subnets['ams1_vpn_coprinus0_private'] }}"
