---
    # first unlock any machines that have rebooted
  - hosts: luks_encrypted_machines
    gather_facts: false
    roles:
      - role: add_to_known_hosts
        ansible_port: 23
        add_to_known_hosts__skip_if_connect_fails: true
      - unlock_luks
