---
    # First unlock any machines that have rebooted
  - hosts: luks_encrypted_machines
    gather_facts: false
    roles:
      - role: add_to_known_hosts
        add_to_known_hosts__skip_if_connect_fails: true
      - role: add_to_known_hosts
        add_to_known_hosts__ssh_port: 23
        add_to_known_hosts__skip_if_connect_fails: true
      - unlock_luks

    # Next, make sure that all of the machines have admin accounts set up and
    # automatic security patches enabled.
  - hosts: all
    gather_facts: false
    become: true
    roles:
      - role: core_setup

    # Set up morchella as a NAT and PXE boot server
  - hosts: morchella
    become: true
    roles:
      - router
      # dhcp_server
      # pxe_boot_server
