---
    # create the install media on the local machine
  - hosts: all
    gather_facts: false
    roles:
       - make_install_media

    # unlock any machines that have rebooted
  - hosts: luks_encrypted_machines
    gather_facts: false
    roles:
      - role: add_to_known_hosts
        add_to_known_hosts__skip_if_connect_fails: true
      - role: add_to_known_hosts
        add_to_known_hosts__ssh_port: 23
        add_to_known_hosts__skip_if_connect_fails: true
      - unlock_luks

    # Make sure that all of the machines have admin accounts set up and
    # automatic security patches enabled.
  - hosts: all
    gather_facts: false
    become: true
    roles:
      - core_setup

    # setup infiniband and ipmi on boletus hosts
  - hosts: boletus
    become: true
    roles:
      - infiniband_setup
      - ipmi_setup
      - role: add_subnet_to_hosts_file
        vars:
            subnet: "{{ oel_subnets.bos1_backhaul }}"

    # Additional core setup tasks
  - hosts: all
    become: true
    roles:
      - network_setup

    # Make sure that all of the machines have admin accounts set up and
    # automatic security patches enabled.
  - hosts: luks_encrypted_machines
    become: true
    roles:
      - update_luks_config
      - network_setup

    # Set up morchella as a NAT and PXE boot server
  - hosts: morchella
    become: true
    roles:
      - role: add_subnet_to_hosts_file
        vars:
            subnet: "{{ oel_subnets.bos1_public }}"
      - role: add_subnet_to_hosts_file
        vars:
            subnet: "{{ oel_subnets.bos1_management }}"
      - router
      - dhcp_server
      - pxe_boot_server
      #- ipmi_viewer
    tasks: # TODO: should be replaced with roles
      - name: additional packages
        apt:
            name: "{{ item }}"
            state: present
        loop:
          - socat # needed for current IPMI UDP tunneling
          - psmisc # for killall, used by IPMI tunneling script
          - ipmitool # useful utility, should go in a role

    # set up the virtual machine hosts
  - hosts: kvm_hosts
    become: true
    roles:
      - kvm_host
