---
  - name: Check SSH known_hosts for host key for port
        {{ add_to_known_hosts__ssh_port }}
    connection: local
    shell: >
        ssh-keygen -F {{ ('{}' if add_to_known_hosts__ssh_port==22 else
        '[{}]:{}').format(inventory_hostname, add_to_known_hosts__ssh_port) }}
    register: ssh_key_check
    failed_when: false
    changed_when: false
    ignore_errors: yes
    become: false

  - name: Add host key for port {{ add_to_known_hosts__ssh_port }} to
        known_hosts if missing
    connection: local
    shell: "{% if ssh_jump_host is defined %} ssh {{ ssh_jump_host }} {%
		endif %}
        ssh-keyscan -p {{ add_to_known_hosts__ssh_port }} {{
		inventory_hostname }}
        >> ~/.ssh/known_hosts"
    register: keyscan_result
    when: ssh_key_check.rc == 1
    changed_when: >
        ssh_key_check.rc == 1 and
        not "Connection refused" in keyscan_result.stderr
    failed_when: >
        "Connection refused" in keyscan_result.stderr and
        not add_to_known_hosts__skip_if_connect_fails
    become: false
