---

  - name: synchronize the manifests directory
    synchronize:
        src: "{{ playbook_dir }}/manifests"
        dest: /var/lib/
        archive: no
        checksum: yes
        recursive: yes
        delete: yes
        links: yes
        use_ssh_args: yes

  - name: apply the manifests
    command: kubectl apply -f {{ item }}
    run_once: true
    register: kube_apply_manifests
    changed_when: "'configured' in kube_apply_manifests.stdout or
        'created' in kube_apply_manifests.stdout"
    loop: "{{ kube_manifests }}"
