---

  - name: synchronize the manifests directory
    synchronize:
        src: "files/manifests"
        dest: /var/lib/
        archive: no
        checksum: yes
        recursive: yes
        links: yes
        use_ssh_args: yes

  - name: for manifests that are templates, generate them if needed
    template:
        src: '{{ item | regex_replace("^template://(.*)$",
            "templates/manifests/\1") }}'
        dest: '{{ item | regex_replace("^template://(.*)$",
            "/var/lib/manifests/\1") }}'
    when: item is search("^template://")
    loop: "{{ kube_manifests }}"

  - name: apply the manifests
    command: kubectl apply -f
        {% if item is search("^template://") %}
            {{ item | regex_replace("^template://(.*)$",
                "/var/lib/manifests/\1") }}
        {% else %}
            {{ item }}
        {% endif %}
    run_once: true
    register: kube_apply_manifests
    # note: 'configured' may also indicate a change, but often not; we accept
    # the occasional false negative changed message rather than always
    # reporting that the server has changed for some manifests.
    changed_when: "'created' in kube_apply_manifests.stdout"
    loop: "{{ kube_manifests }}"
