---
network_interfaces:
    enp1s0:
        subnet: "{{ oel_subnets.bos1_vpn_boletus2_private }}"

kvm_volumes_used:
  - ssd0_pool/venus2_root

ssh_jump_host: "{{ lookup('env', 'USER')
    }}admin@boletus2.bos1.openelectronicslab.org"

ansible_ssh_common_args: "-oServerAliveInterval=3 -oProxyJump={{ ssh_jump_host | default(omit) }}"
