---
# Secrets for the oel nextcloud instance
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: nextcloud-secret
data:
    db_admin_password: {{ oel_nextcloud_db_admin_password | b64encode }}
    db_password: {{ oel_nextcloud_db_password | b64encode }}
    admin_password: {{ oel_nextcloud_admin_password | b64encode }}
---
# Persistent volume claim for block storage for the database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nextcloud-db-pvc
    labels:
        app: nextcloud
spec:
    storageClassName: ceph-block-sc
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi
---
# Deployment for the database
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nextcloud-db
    labels:
        app: nextcloud
spec:
    selector:
        matchLabels:
            app: nextcloud
            tier: db
    template:
        metadata:
            labels:
                app: nextcloud
                tier: db
        spec:
            containers:
              - name: nextcloud-mariadb
                image: mariadb:10.5
                env:
                  - name: MYSQL_ROOT_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: nextcloud-secret
                            key: db_admin_password
                  - name: MYSQL_DATABASE
                    value: nextcloud
                  - name: MYSQL_USER
                    value: nextcloud
                  - name: MYSQL_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: nextcloud-secret
                            key: db_password
                ports:
                  - containerPort: 3306
                volumeMounts:
                  - name: mariadb-persistent-storage
                    mountPath: /var/lib/mysql
            volumes:
              - name: mariadb-persistent-storage
                persistentVolumeClaim:
                    claimName: nextcloud-db-pvc
    # destroy the old node before creating the new (to avoid two nodes
    # accessing the storage at the same time):
    strategy:
        type: Recreate
---
# Define a service for the database
apiVersion: v1
kind: Service
metadata:
    name: nextcloud-db-service
    labels:
        app: nextcloud
spec:
    selector:
        app: nextcloud
        tier: db
    ports:
      - port: 3306
    # disable kubernetes's load balancing and proxying:
    #clusterIP: None

---
# Persistent volume claim for file storage for /var/www/html of nextcloud
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nextcloud-files-pvc
    labels:
        app: nextcloud
        tier: frontend
spec:
    accessModes:
      - ReadWriteMany
    resources:
        requests:
            storage: 4Ti
    storageClassName: ceph-filesystem-sc
---
# Deployment for the front-end nextcloud web servers
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nextcloud-frontend
    labels:
        app: nextcloud
spec:
    selector:
        matchLabels:
            app: nextcloud
            tier: frontend
    replicas: 1
    template:
        metadata:
            labels:
                app: nextcloud
                tier: frontend
        spec:
            containers:
              - name: nextcloud-frontend
                image: nextcloud:19
                env:
                  - name: MYSQL_DATABASE
                    value: nextcloud
                  - name: MYSQL_USER
                    value: nextcloud
                  - name: MYSQL_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: nextcloud-secret
                            key: db_password
                  - name: MYSQL_HOST
                    value: nextcloud-db-service
                    #value: nextcloud-db-service.default.svc.cluster.local
                  - name: NEXTCLOUD_ADMIN_USER
                    value: nextcloud_admin
                  - name: NEXTCLOUD_ADMIN_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: nextcloud-secret
                            key: admin_password
                  - name: NEXTCLOUD_TRUSTED_DOMAINS
                    value: nextcloud.kendrickshaw.org
                        nextcloud.openelectronicslab.org
                ports:
                  - containerPort: 80
                volumeMounts:
                  - name: html-volume
                    mountPath: /var/www/html
            volumes:
              - name: html-volume
                persistentVolumeClaim:
                    claimName: nextcloud-files-pvc
                    readOnly: false
---
# Service for the nextcloud front-end web servers
apiVersion: v1
kind: Service
metadata:
    name: nextcloud-service
    labels:
        app: nextcloud
spec:
    selector:
        app: nextcloud
        tier: frontend
    ports:
      - port: 80
        protocol: TCP
---
# Ingress for nextcloud from nextcloud.kendrickshaw.org
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nextcloud-kso-ingress
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
    tls:
      - hosts:
          - nextcloud.kendrickshaw.org
        secretName: nextcloud-kendrickshaw-org-tls
    rules:
      - host: nextcloud.kendrickshaw.org
        http:
            paths:
              - pathType: Prefix
                path: /
                backend:
                    service:
                        name: nextcloud-service
                        port:
                            number: 80
---
# Ingress for nextcloud from nextcloud.openelectronicslab.org
# TODO: turn on TLS support once DNS points at this server
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nextcloud-oel-ingress
#    annotations:
#        cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
#    tls:
#      - hosts:
#          - nextcloud.openelectronicslab.org
#        secretName: nextcloud-openelectronicslab-org-tls
    rules:
      - host: nextcloud.openelectronicslab.org
        http:
            paths:
              - pathType: Prefix
                path: /
                backend:
                    service:
                        name: nextcloud-service
                        port:
                            number: 80
