---
  - name: restart keepalived
    service:
        name: keepalived
        state: restarted
        enabled: true

  - name: restart haproxy
    service:
        name: haproxy
        state: restarted
        enabled: true

