---
# tasks file for unlock_luks
  - name: Unlock encrypted root drive
    block:
      - name: check if the server is already available with the user account
        wait_for_connection:
            timeout: 5
    tags: luks
    rescue:
      # computer locked or user accounts not yet created
      - block:
          - name: check if the server is already available with root
            vars:
                ansible_user: root
            wait_for_connection:
                timeout: 5
        rescue:
          # computer locked
          - name: Unlock the root filesystem with the assigned passphrase
            block:
              - name: send the unlock string
                local_action: command /bin/bash -c
                    "printf \"{{ luks_password }}\" |
                        ssh {{ ansible_ssh_common_args | default("") }}
                            root@{{ inventory_hostname }} -p 23"
                no_log: true
              - name: wait for the server to come up to confirm that it
                    successfully unlocked
                wait_for_connection:
                    connect_timeout: 1
                    timeout: 30
            rescue:
              # computer locked, and real luks password is not set
              - block:
                  - name: unlock the root filesystem with the installer's
                        default passphrase.
                    local_action: command /bin/bash -c
                        "printf \"temp\" |
                            ssh {{ ansible_ssh_common_args | default("") }}
                                root@{{ inventory_hostname }} -p 23"
                    #no_log: true
                  - name: wait for the server to come up to confirm that it
                        successfully unlocked (using root)
                    vars:
                        ansible_user: root
                    wait_for_connection:
                        timeout: 30
                    connection: local
                rescue:
                  # if crash after user setup, but before luks password is set
                  - name: wait for the server to come up to confirm that it
                        successfully unlocked (using user account)
                    wait_for_connection:
                        timeout: 30
                    connection: local
          - name: extra delay for machine to boot
            pause:
                seconds: 30
