---
  - name: configure the network interfaces
    copy:
        dest: /etc/network/interfaces.d/50-{{ item.key }}
        content: |
            auto {{ item.key }}
            iface {{ item.key }} inet static
                address {{
                    item.value.subnet.hosts[inventory_hostname_short].ip }}
                broadcast {{ item.value.subnet.broadcast }}
                netmask {{ item.value.subnet.netmask }}
            {% if item.key == primary_interface %}
                gateway {{ item.value.subnet.gateway }}
            {% endif %}
            {% if item.value.subnet.mtu is defined %}
                mtu {{ item.value.subnet.mtu }}
            {% endif %}
            {% if item.value.pre_up is defined %}
            {% for line in item.value.pre_up %}
                pre-up {{ line }}
            {% endfor %}
            {% endif %}
            {% for hostname,hostvals in item.value.subnet.hosts.items() %}
            {% if hostname != inventory_hostname_short and
                hostvals.subnets is defined%}
            {% for subnet in hostvals.subnets %}
                post-up ip route add {{ subnet }} via {{ hostvals.ip }}
                pre-down ip route del {{ subnet }} via {{ hostvals.ip }}
            {% endfor %}
            {% endif %}
            {% endfor %}
    register: network_interface_changes
    with_dict: "{{ network_interfaces }}"
    notify: restart network interfaces
