---
  - name: configure the network interfaces
    copy:
        dest: /etc/network/interfaces.d/50-{{ item.key }}
        content: |
            auto {{ item.key }}
            iface {{ item.key }} inet static
                address {{
                    item.value.subnet.hosts[inventory_hostname_short].ip }}
                broadcast {{ item.value.subnet.broadcast }}
                netmask {{ item.value.subnet.netmask }}
            {% if item.key == primary_interface %}
                gateway {{ item.value.subnet.gateway }}
            {% endif %}
            {% if item.value.mtu is defined %}
                mtu {{ item.value.mtu }}
            {% endif %}
            {% if item.value.pre_up is defined %}
            {% for line in item.value.pre_up %}
                pre-up {{ line }}
            {% endfor %}
            {% endif %}
    register: network_interface_changes
    with_dict: "{{ network_interfaces }}"
    notify: restart network interfaces
