---
  - name: add hosts from {{ subnet.name }} subnet to /etc/hosts
    lineinfile:
        path: /etc/hosts
        regexp: '\b{{ item.key }}\.{{ subnet.name }}\b'
        line: "{{ item.value.ip }} {{ item.key }}.{{ subnet.name }}"
    with_dict: "{{ subnet.hosts }}"
    #loop: "{{ subnet.hosts | dict2items }}"

