---
  - name: install curl
    apt:
        name: curl
        state: present

  - name: check for legacy iptables
    shell: ls -l /etc/alternatives/iptables
    register: alternatives_iptables
    changed_when: false

  - name: Workaround for systemd overwriting flannel mac addresses (flannel bug 1155)
    copy:
        dest: /etc/systemd/network/10-flannel.link
        mode: 0755
        content: |
            [Match]
            OriginalName=flannel*

            [Link]
            MACAddressPolicy=none

  - name: switch to legacy iptables
    shell: |
        iptables -F;
        update-alternatives --set iptables /usr/sbin/iptables-legacy;
        update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
    when: not 'legacy' in alternatives_iptables.stdout

  - name: reboot after changing iptables to legacy
    reboot:
    when: not 'legacy' in alternatives_iptables.stdout

  - name: Install LVM (for Rook OSDs)
    apt:
        name: lvm2
        state: present

  - name: Start kubernetes workers
    shell:
        cmd: export K3S_TOKEN={{ k3s_token }};
            curl -sdL https://get.k3s.io | sh -s - agent --server
              https://{{ kube_control_plane_ip }}:{{ kube_control_plane_port }}
        creates: /usr/local/bin/k3s
    failed_when: false # TODO: the command line can timeout while the process
                       # continues and install eventually succeeds.

  - name: install the libvirt daemon for kubevirt
    apt:
        name: libvirt-daemon-system
        state: present

    # See https://github.com/kubevirt/kubevirt/issues/4303
  - name: Patch libvirtd apparmor profile for kubevirt conflict
    lineinfile:
        path: /etc/apparmor.d/local/usr.sbin.libvirtd
        line: '  /usr/libexec/qemu-kvm PUx,'
    register: libvirtd_apparmor_patch

  - name: reload patched apparmor profile
    command: apparmor_parser -r /etc/apparmor.d/usr.sbin.libvirtd
    when: libvirtd_apparmor_patch.changed
