  - name: generate the old LUKS keyfile
    copy:
        dest: /root/default_luks_password
        content: temp

  - name: generate the new LUKS keyfile
    copy:
        dest: /root/luks_password
        content: "{{ luks_password }}"

  - name: identify the partition with the encrypted root drive
    shell: >
        echo $(cat /etc/crypttab
        | cut -f 2 -d' '
        | sed -e's@UUID=@/dev/disk/by-uuid/@g' -)
    register: luks_device_path
    changed_when: false
    # TODO: handle the case where we have more than one encrypted drive


  - name: Check if the temporary luks password is still set
    command: >
        cryptsetup luksOpen
        {{ luks_device_path.stdout }}
        --test-passphrase
        --key-file /root/default_luks_password
    register: luks_temp_password_result
    changed_when: false
    failed_when: false

  - name: Change the luks encryption password if needed
    block:
      - name: add the new LUKS password
        command: >
            cryptsetup luksAddKey
            {{ luks_device_path.stdout }}
            /root/luks_password
            --key-file /root/default_luks_password
      - name: add the new LUKS password
        command: >
            cryptsetup luksRemoveKey
            {{ luks_device_path.stdout }}
            --key-file /root/default_luks_password
    when: luks_temp_password_result.rc == 0

  - name: configure the dropbear adapter
    lineinfile:
        path: /etc/dropbear-initramfs/config
        regexp: '^IP='
        line: IP={{
            network_interfaces[primary_interface].subnet
            .hosts[inventory_hostname_short].ip }}::{{
            network_interfaces[primary_interface].subnet.gateway }}:{{
            network_interfaces[primary_interface].subnet.netmask }}:{{
            inventory_hostname_short }}:{{
            primary_interface }}:off
    notify: rebuild initramfs

  - name: Set the dropbear authorized keys
    authorized_key:
        user: root
        state: present
        path: /etc/dropbear-initramfs/authorized_keys
        key_options: 'no-port-forwarding,no-agent-forwarding,no-x11-forwarding,command="/bin/cryptroot-unlock"'
        key: "{{ lookup('file',
                 'secrets/ssh-keys/' + item.username + '.keys') }}"
    loop: "{{ admin_users }}"
    notify: rebuild initramfs
